docs: add lidar requirements document
open-v2x/docs pull request #105
Opened 2022-10-14 08:48 UTC by lin-fuyu

closes: issue #104

2022-10-14 09:06 UTC, wu-wenxiang requested changes

2022-10-14 09:06 UTC, wu-wenxiang commented on spec/lidar.md
> +
多余的空格

2022-10-14 09:06 UTC, wu-wenxiang commented on spec/lidar.md
> +   - 禁用：禁用中表示禁止使用该雷达设备，不允许该设备上传、下发消息。点击“启用”按钮，将该设备状态变更为启用中。
缩进

2022-10-14 09:06 UTC, wu-wenxiang commented on spec/lidar.md
> +
不必要的空格

2022-10-18 02:17 UTC, FrankGTY approved these changes

2022-10-21 07:22 UTC, wu-wenxiang commented on spec/lidar.md
> +- “纬度”：输入该雷达安装的实际纬度。
缺少缩进

2022-10-21 07:22 UTC, wu-wenxiang commented on spec/lidar.md
> +
多余空行 & 缺少缩进

2022-10-21 07:24 UTC, wu-wenxiang commented on spec/lidar.md
> +- 在线率=设备在线数 / 激光雷达设备总数
缩进

2022-10-21 08:38 UTC, cmycoups approved these changes

2022-10-24 02:59 UTC, wu-wenxiang approved these changes

2022-10-24 03:00 UTC, merged